### ISSUE TITLE
WHM not receiving authorisation if launched when SAFE browser (and authenticator) closed.

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe-web-hosting-manager-electron#20]
Launching WHM when SAFE browser is not currently open does not function properly.

See attached document for details of different scenarios:

https://docs.google.com/document/d/1ITjmX6rLKEYct4mtzis_wGNnAa3WbIFRs0SogE1x6wE/edit

**Comment by joshuef** [comment]
This is actually a browser issue, sorted by https://github.com/maidsafe/safe_browser/pull/472

**Comment by joshuef** [comment]
The expected behaviour is that the browser receives the auth Req, but throws an 'unauthed' error (as not logged in).

The WHM will _still_ not receive auth, but an error will be shown browser side.
